services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks: [mern-network]

  auth:
    build: ./backend-auth
    container_name: auth
    env_file: ./backend-auth/.env
    networks: [mern-network]

  todo:
    build: ./backend-todo
    container_name: todo
    env_file: ./backend-todo/.env
    networks: [mern-network]

  profile:
    build: ./backend-profile
    container_name: profile
    env_file: ./backend-profile/.env
    networks: [mern-network]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    networks: [mern-network]

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html    
    depends_on:
      - auth
      - todo
      - frontend
      - profile
    networks: [mern-network]

networks:
  mern-network:
    driver: bridge

volumes:
  mongo_data:
